# RAIZ
root:
    path: /
    controller: App\Controller\SecurityController::redirectToLogin 

# LOGIN -> ADMIN & USUARIO NORMAL
login:
    path: /login
    controller: App\Controller\SecurityController::login

# LOGOUT -> ADMIN & USUARIO NORMAL
logout:
    path: /logout
    controller: App\Controller\SecurityController::logout


######################################################################
#   USUARIO
######################################################################
# REGISTRAR USUARIOS -> ADMIN
usuario_new:
    path: /registro/usuario/{id}
    controller: App\Controller\UserController::new

usuario_show:
    path: /usuario/{id}
    controller: App\Controller\UserController::show
    methods: ['GET']

contacto_new:
    path: /dashboard/contacto/{id}
    controller: App\Controller\ContactoController:new


######################################################################
#   DASHBOARD DE GRANOTA  -> ADMIN
######################################################################
dashboard_index:
    path: /dashboard
    controller: App\Controller\DashboardController::index

dashboard_clientes:
    path: /dashboard/clientes
    controller: App\Controller\DashboardController::clientes

dashboard_briefings:
    path: /dashboard/briefings
    controller: App\Controller\DashboardController::briefings

dashboard_contenidos:
    path: /dashboard/contenidos
    controller: App\Controller\DashboardController::contenidos

dashboard_incidencias:
    path: /dashboard/incidencias
    controller: App\Controller\DashboardController::incidencias



######################################################################
#   DASHBOARD DEL CLIENTE (EMPRESA)  -> USUARIO NORMAL
######################################################################
dashboard_empresa:
    path: /inicio
    controller: App\Controller\DashboardClienteController::index



######################################################################
#   CRUD    EMPRESA  -> ADMIN
######################################################################

empresa_new:
    path: /registro/empresa
    controller: App\Controller\EmpresaController::new
    methods: ['GET', 'POST']

empresa_show:
    path: /dashboard/clientes/{id}
    controller: App\Controller\EmpresaController::show
    methods: ['GET']

empresa_edit:
    path: /dashboard/clientes/edit/{id}
    controller: App\Controller\EmpresaController::edit
    methods: ['GET', 'POST']

empresa_delete:
    path: /dashboard/clientes/{id}
    controller: App\Controller\EmpresaController::delete
    methods: ['POST']

web_new:
    path: /dashboard/clientes/web/{id}
    controller: App\Controller\WebController::new
    methods: ['GET', 'POST']



#######################################################################
#   CRD + PDF   BRIEFINGS 
#######################################################################

#-------- APP -------------#

briefing_app_new:
    path: /inicio/briefingapp
    controller: App\Controller\BriefingAppController::new
    methods: ['GET']

briefing_app_show:
    path: /dashboard/briefings/briefing-app/{id}
    controller: App\Controller\BriefingAppController::show
    methods: ['GET']

briefing_app_delete:
    path: /dashboard/briefings/{id}
    controller: App\Controller\BriefingAppController::delete
    methods: ['POST']

briefing_app_pdf:
    path: /briefing-app/{id}/descargar-pdf
    controller: App\Controller\BriefingAppController::descargarPDF
    methods: ['GET']

#-------- WEB -------------#
briefing_web_new:
    path: /inicio/briefingweb
    controller: App\Controller\BriefingWebController::new
    methods: ['GET']

briefing_web_show:
    path: /dashboard/briefings/briefing-web/{id}
    controller: App\Controller\BriefingWebController::show
    methods: ['GET']

briefing_web_delete:
    path: /dashboard/briefings/{id}
    controller: App\Controller\BriefingWebController::delete
    methods: ['POST']

briefing_web_pdf:
    path: /briefing-web/{id}/descargar-pdf
    controller: App\Controller\BriefingWebController::descargarPDF
    methods: ['GET']

#-------- LOGO -------------#

briefing_logo_new:
    path: /inicio/briefinglogo
    controller: App\Controller\BriefingLogoController::new

briefing_logo_show:
    path: /dashboard/briefings/briefing-logo/{id}
    controller: App\Controller\BriefingLogoController::show
    methods: ['GET']

briefing_logo_delete:
    path: /dashboard/briefings/{id}
    controller: App\Controller\BriefingLogoController::delete
    methods: ['POST']

briefing_logo_pdf:
    path: /briefing-logo/{id}/descargar-pdf
    controller: App\Controller\BriefingLogoController::descargarPDF
    methods: ['GET']



#######################################################################
#   CRD + PDF  CONTENIDO
#######################################################################
contenido_new:
    path: /inicio/contenido
    controller: App\Controller\ContenidoController::new
    methods: ['GET']

contenido_show:
    path: /dashboard/contenido/{id}
    controller: App\Controller\ContenidoController::show
    methods: ['GET']

contenido_delete:
    path: /dashboard/ontenido/{id}
    controller: App\Controller\ContenidoController::delete
    methods: ['POST']

contenido_pdf:
    path: /dashboard/contenido/{id}/descargar-pdf
    controller: App\Controller\ContenidoController::descargarPDF
    methods: ['GET']



#######################################################################
#   CRD + PDF   INCIDENCIA
#######################################################################
incidencia_new:
    path: /inicio/incidencia
    controller: App\Controller\IncidenciasController::new
    methods: ['GET']

incidencia_show:
    path: /dashboard/incidencias/{id}
    controller: App\Controller\IncidenciasController::show
    methods: ['GET']

incidencia_delete:
    path: /dashboard/incidencias/{id}
    controller: App\Controller\IncidenciasController::delete
    methods: ['POST']

incidencia_pdf:
    path: /dashboard/incidencias/{id}/descargar-pdf
    controller: App\Controller\IncidenciasController::descargarPDF
    methods: ['GET']